### ISSUE TITLE
Garmin Varia 515

### ISSUE THREAD

**Issue by HarveyDent1** [maca88/SmartBikeLights#1]
Hello, 
Could you consider add to service taillight from radar Garmin Varia RTL 515 ? 
Congratulation ! Excellent job. I'll be happy to make a donation for you.

**Comment by maca88** [comment]
Hi,

sure, but I need someone that has it in order to understand what modes the light supports. In case you have the mentioned light and a touch screen edge device please check this post: https://forums.garmin.com/developer/connect-iq/f/showcase/248492/data-field-smart-bike-light

**Comment by maca88** [comment]
The light is now available in the Lights configurator.
