### ISSUE TITLE
Cannot Set Control Mode

### ISSUE THREAD

**Issue by simonf00** [maca88/SmartBikeLights#27]
Hello,

First, I'd like to thank you for all your efforts on this project!!

I'm trying to use your data field with my Edge 530 and Varia RTL 515. I've installed the data field, paired the Varia, set the Light Beam Activated setting to Timer Start and set up a configuration with the Lights Configurator. Everything looks to be ok at this point as I can see, save and change the configuration in the IQC settings. The problem I'm running into is that when I try to change the Control Mode on the data screen where I have the data field, I select Connect IQ -> Smart Bike Lights, but trying to go into the settings for Control Mode, nothing happens. I'm stuck on the Connect IQ screen listing the Smart Bike Light app (see attached screenshot). I'm stuck at that step. On the Data Screen itself, it's showing I'm in "N" mode (see 2nd attached screenshot).

Any hints on how to get past this would be appreciated.

Thanks,
Simon.

![IMG_6889](https://user-images.githubusercontent.com/389931/167281289-7a8daa32-907b-41ad-8498-5edc019ca4cc.jpg)
![IMG_6892](https://user-images.githubusercontent.com/389931/167281348-b427c053-3d4a-4f85-822a-b5980b5f3077.jpg)

**Comment by maca88** [comment]
Hi,

can you provide the configuration that you created by using Lights Configurator, so that I can test it?

**Comment by simonf00** [comment]
Thanks for taking the time to check into this. Here's the config:

###0,73535488#3,2!Detect:2:7:1:0H]1I]-1]0!:1:0:0:0D=1##6:Varia 515!null:-1!Off:0!Solid:4!Peloton:5!Day Flash:7!Night Flash:6#0::#0:0#B3121##3#0#0

**Comment by simonf00** [comment]
Works!! Thanks so much for your help, @maca88.

I tried to reproduce the `null:-1!` but unfortunately, I couldn't. I think when I initially created the config I used an example someone posted on one of the Garmin forums and changed the device from Edge 1030 to Edge 530. Maybe that has something to do with it? In any event, I tried, but couldn't get the error to show up.

**Comment by maca88** [comment]
> Maybe that has something to do with it?

It could be, but I cannot confirm as I also wasn't been able to reproduce it yet. Closing this issue and will open another once we will know how to reproduce it.
