### ISSUE TITLE
Updated Edge 530 to software version 9.40 now lights say "No network"

### ISSUE THREAD

**Issue by my1e5** [maca88/SmartBikeLights#28]
My Garmin Edge 530 updated to software version 9.40 and now my lights have stopped working with this app. I have a Garmin Varia rear light and a Bontrager Ion Pro RT front light.  Had no problems previously. My rear and front light would automatically switch on when I powered on my Edge 530 and their mode/battery status would be displayed on its data field. Now the lights don't come on and the data field shows "No network". My Varia radar function is still working. I can only assume this is related to my Edge 530 updating to software version 9.40? 

<img src="https://user-images.githubusercontent.com/10064103/168270499-136fd5f9-660d-4a52-9bec-c64d54fe95e8.jpeg" data-canonical-src="https://user-images.githubusercontent.com/10064103/168270499-136fd5f9-660d-4a52-9bec-c64d54fe95e8.jpeg" width="200"  />

I will try removing my lights and re-adding them - maybe that will fix it? But so far I can't work out how to remove my lights - there doesn't seem to be a remove option when in the Sensors menu (I suppose this is unrelated to the Smart Bike Lights so I will check with Garmin).

<img src="https://user-images.githubusercontent.com/10064103/168270881-4cbbd54f-b591-43d0-abc0-0b05546d8cef.jpeg" data-canonical-src="https://user-images.githubusercontent.com/10064103/168270881-4cbbd54f-b591-43d0-abc0-0b05546d8cef.jpeg" width="200"  /><img src="https://user-images.githubusercontent.com/10064103/168271081-d89ac21a-460e-42bc-b386-da2c8f21432b.jpeg" data-canonical-src="https://user-images.githubusercontent.com/10064103/168271081-d89ac21a-460e-42bc-b386-da2c8f21432b.jpeg" width="200"  />

Anyway, just want to report this here in case other users have experienced this. Thank you maca88 for the great app btw! Hope I can fix it.

**Comment by maca88** [comment]
> I will try removing my lights and re-adding them - maybe that will fix it?

Based on the images, both lights have the `?` symbol inside the battery, which means that they are not connected to the Garmin. I think that by re-adding them it should fix the issue.

**Comment by my1e5** [comment]
Successfully managed to restore functionality. For some reason, under 'Lights' in the Sensors list there isn't a Remove option like other sensor menus seem to have. This confused me for a while. But what I did was remove my Radar from it's specific radar menu. This removed it from Lights. Then I re-added the Radar after resetting it. For my Bontrager Ion Pro RT front light I held down the power button for 15 seconds (which supposedly is the way to reset it). And for some reason that just caused it to automatically start working again. Didn't have to do anything else.

**Comment by gitthangbaby** [comment]
Hello. I have this problem too, except it happens over and over every day. Bontrager RT lights get disconnected and  I fix "?" connection by simply searching for sensors and cancelling.   Is "Individual Light Network" approach eventually going to help?

**Comment by maca88** [comment]
Hi,

based on the description it seems like that your Garmin has a problem maintaining a stable connection to your Bontrager RT lights. I saw on Garmin forums people having similar issues and for some of them, the issue disappeared when disabling Bluetooth. I am not sure whether "Individual Light Network" will help you, but you can still try it. If using "Individual Light Network" also doesn't help, then I would suggest to report the issue to Garmin.

**Comment by gitthangbaby** [comment]
> 

thanks a lot. Disabling Bluetooth would disable ANT so this is not welcome. I actually read every single related thread incl your app discussion. So far the only suggestion is to stop using sleep, instead fully shutdown the Garmin device. As the devices perfectly work when Garmin is sleeping for a limited time. The "Individual Light Network" is interesting it does contact ANT devices independently, unlike Garmin or Bontrager app. I will try everything but the testing is time consuming, 1 test per day basically. Will post if I come to solution.

**Comment by my1e5** [comment]
@gitthangbaby - my advice is to never use sleep mode. Every time I'm finished with my ride, I fully shutdown my 530. This has worked pretty well for me for the last year. Occasionally, I'll get a no network error or another error code, but usually restarting the device fixes it. But it's much more stable and reliable this way. Haven't had to re-pair the lights in a long while. So yeah, avoid sleep, instead fully shutdown your device every time. I haven't searched the Garmin forums for a while, so would be interesting to know if there are any other solutions.

**Comment by gitthangbaby** [comment]
> my advice is to never use sleep mode.

Thanks for valuable feedback. In todays test, lights turned on indeed. Also the lights battery didn't drop yet in standby mode suggesting the ANT mode is power saving (as it should be).

**Comment by my1e5** [comment]
I just updated by 530 to software version 9.75. On first startup after the update, my Varia radar didn't connect. So I restarted the device and then it connected fine. Just done 4 on/off cycles and both my smart lights seem to be working fine. Also (I think it was like this before as well), but it will show No Network at first, but then if you wait 30s or so, it will connect. As I said, sometimes it can be buggy, but if you restart it should be fine. And if you avoid putting the 530 to sleep and always fully shutting down, then the permanent No Network bug never seems to happen.

**Comment by gitthangbaby** [comment]
Today only one light connected after shutdown and 24hr wait. So it's still bad even with inconvenient full shutdown. All it takes to reconnect is to search for sensors and cancel that. I wish we could incorporate search action to SmartBikeLights. I really don't want to keep doing restarts or searches, that's insane.

**Comment by gitthangbaby** [comment]
This problem is fixed with Individual Light Network. That one just works. It always connects. It visibly reconnects even when going further from the ANT device and back. Now I can put the device to sleep. Thanks a lot!
