### ISSUE TITLE
Edge 530 manual mode

### ISSUE THREAD

**Issue by jamesholcomb** [maca88/SmartBikeLights#3]
I have an Edge 530 (no touch screen) and Flare RT and have setup according to the README (data field and widget installed and sync, pasted this value into the app for Lights Configurator using the defaults:

`###6291461,1409482753#1,1|:1:7:1D=1##6:Flare RT|Off:0|Day Steady:1|Night Steady:5|Day Flash:7|All-Day Flash:8|Night Flash:63#B3121##1#1#1`

I would like to turn the light on and off using manual mode from a data screen.

My data screen 2 shows the Flare RT (mode=N along with battery level).  Pressing menu from the screen brings up the menu, but I see no item for "Smart Bike Lights" (only "Light Network").

Any ideas?  I'm on latest FW.

Update 1: I can get to the Flare RT control screen via Status | Widgets
Update 2: Could it be possible to control light on/off using the WatchUi.KEY_LAP?

**Comment by maca88** [comment]
> Pressing menu from the screen brings up the menu, but I see no item for "Smart Bike Lights" (only "Light Network").

There was a bug that prevented the settings to show up when only one light was paired. Update to the newly released version `0.10.1` and "Smart Bike Lights" should appear after holding the menu button for a few seconds. Please let me know whether it works.

> Could it be possible to control light on/off using the WatchUi.KEY_LAP?

Unfortunately data field applications do not have the ability to detect a button press.

In case you just want to manually control the light you can install the widget instead, but make sure to download version 0.5.5 (should be released in one hour) as the same bug is present also for the widget:
https://apps.garmin.com/en-US/apps/fa3c2332-76e3-4ba1-8528-32a0fd617ab1

Thanks for reporting the issue.

**Comment by jamesholcomb** [comment]
I installed both updates but it did not make a difference for me.  Here's I how tested after sync and reboot:

Main screen
Menu button
Road activity
Start ride (tail light comes on)
Page down to screen 2 which shows status N, battery level, ON
"Hold the menu button for a few seconds" (nothing happens)
If I just press menu, the menu opens but does not show Smart Bike Lights

Essentially, I am looking for the shortest workflow possible to turn on/off the light from a data screen.  I can use the widget but it's a lot of button pressing and focusing.  I guess I should have bought the 830 :-)

**Comment by maca88** [comment]
> "Hold the menu button for a few seconds" (nothing happens)

Please try holding the "Up" button instead of the "Menu" button, from what I found on the Garmin forums (https://forums.garmin.com/developer/connect-iq/f/discussion/237508/sdk-3-2-on-device-settings/1127318#1127318) it seems to be the "Up" button for most devices.


> I am looking for the shortest workflow possible to turn on/off the light from a data screen

Do you have a pattern when you need to turn on/off the light? For example, in case you need to turn on the light on sunset you can use the "Timespan" filter in the Lights Configurator:

```1,1|:1Es0,r0###6291461,1409482753#1,1|:1:5:1D=1##6:Flare RT|Off:0|Day Steady:1|Night Steady:5|Day Flash:7|All-Day Flash:8|Night Flash:63#B3121##1#0#0```

**Comment by jamesholcomb** [comment]
Holding "up" cycles through the data screens.

Yes and it's mostly ad hoc.  Typical flow for initiating "ride to the ride" from my house:

- Turn on computer
- Start ride (light flashing)
- Ride a couple of miles on streets to the trail
- Reach trail, turn off light, ride for several miles
- Reach start of the real ride, route is 30+ miles on streets
- Turn on light if it's a small group, leave it off it's a big peloton

**Comment by maca88** [comment]
> Holding "up" cycles through the data screens.

That is strange, I asked on Garmin forums (on the above thread) if anyone knows how to open it. I will post it here in case I get an answer.

> Yes and it's mostly ad hoc.

I see, for the trail you could use the "Location" filter to draw your trail regions, but for group rides there is no way to detect that.

> I guess I should have bought the 830 :-)

A cheaper alternative is to buy a "Bontrager Transmitr MicroRemote" to control your light. With it you can double press the button to turn on the light, single press to switch the light mode and hold it to turn off the light.

**Comment by maca88** [comment]
[On the forum](https://forums.garmin.com/developer/connect-iq/f/discussion/237508/sdk-3-2-on-device-settings/1229688#1229688) I got the following answer for changing the data field settings:

> I single press the top-right button, then scroll-down to "Data Fields", then scroll-down to "Connect IQ data fields", then choose the IQ datafield I want to edit settings for.

Unfortunately it seems that it is still a lot of button pressing to get to the menu.

**Comment by jamesholcomb** [comment]
Thanks for the follow up.
