### ISSUE TITLE
0.27 on Edge 530 Smart Mode missing

### ISSUE THREAD

**Issue by stingrayx** [maca88/SmartBikeLights#79]
Hello,

first of all thanks a lot for your excellent work. Highly appreciated!

I'm using SmartBikeLights since several month on two Varia 515 and on two Edge 530 (my son is using the same setup).

Since some days on my bike the Smart mode is not working anymore. As you can see in the picture attached, the mode is not there in the settings menu, whereas everything is correctly paired, a filter is set etc.

Now I'm not a Monkey C expert and never developed a Garmin IQ app, but I searched a bit in your commits and I saw that with the latest version a lot of changes have been done on what is inside the lightData Array, notable on index 17 & 18, mainly in the file BikeLightsView.mc
It seems that inside LightsSettings.mc you are also checking the content of the lightData Array. And when there is nothing at position 17, you continue and no "SMART (S)" is displayed.

Could that be the root of the problem?

On my son's bike all is still ok, but he is using an older version, because he does not regularly connect the Edge to Garmin Express, hence he doesn't receive the updates that quick.

I'm ready to support with doing some tests if needed. Maybe there is a way to install a former version manually?

Thanks a lot for your support.

Best regards
Thomas

![Garmin_530_SMART_Missing](https://github.com/user-attachments/assets/0f220645-84d1-482b-b367-b6bc287f9fa2)

**Comment by Skapik88** [comment]
Hello All,
I have same problem in Epix2 gen. I have types of blinking but missing Smart Mode... Only network and Manual.
Thank you

**Comment by maca88** [comment]
Hi,

> It seems that inside LightsSettings.mc you are also checking the content of the lightData Array. And when there is nothing at position 17, you continue and no "SMART (S)" is displayed.

Your are right, that is exactly the issue. I completely forgot to update the index in the `LightsSettings.mc` after adding the additional lights modes in version `0.27.0``. I do apologize for the inconvenience. Now the issue should be fixed in version `0.27.1`.

**Comment by stingrayx** [comment]
SMART is back! Thanks a lot!
